import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "@/app/provider";
import Header from "@/components/LayoutComponents/Header";
import Body from "@/components/LayoutComponents/Body";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        layout: {
          helpPageUrl: "https://clerk.dev/support",
          logoImageUrl: "https://clerk.dev/logo.png",
          logoPlacement: "inside",
          privacyPageUrl: "https://clerk.dev/privacy",
          showOptionalFields: true,
          socialButtonsPlacement: "bottom",
          socialButtonsVariant: "iconButton",
          termsPageUrl: "https://clerk.dev/terms",
        },
      }}
    >
      <html lang="en">
        <Body>
          <div className="flex min-h-screen flex-col justify-between">
            <Header />
            <Providers>{children}</Providers>
          </div>
        </Body>
      </html>
    </ClerkProvider>
  );
}
